name: date_range_selector
description: A customizable Flutter date range picker with elegant UI and flexible color options.
version: 1.0.2

homepage: https://github.com/Anthony20602/date_range_selector
repository: https://github.com/Anthony20602/date_range_selector
issue_tracker: https://github.com/Anthony20602/date_range_selector/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

screenshots:
  - description: Date range selector preview
    path: assets/screenshots/range_selector.png

flutter:
  uses-material-design: true
